import "./globals.scss";
import { Poppins } from "next/font/google";
import Nav from "./components/Nav";
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({
  weight: ["500", "600", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["devanagari"],
  display: "swap",
});

export const metadata = {
  title: "Luleå Biograf",
  description: "Generated by create next app",
};

interface RootProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <Nav />

        <main className="main-container sec">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
